version: "2"
services:
  web:
    build: 
      context: ./web
    command: "sleep infinity"
    volumes:
      - ./web:/app
    ports:
      - 5000:5000
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
  db:
    image: postgres:15.2-bullseye
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local